apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: vinod
data:
  prometheus.properties: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "node-exporter"
        scrape_interval: 15s
        scrape_timeout: 15s
        scheme: http
        metrics_path: /metrics
        static_configs:
          - targets: ["localhost:9250"]
