apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: vinod
  labels:
    app: prometheus-service
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9090
#      nodePort: 30000