apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: vinod
  labels:
    app: prometheus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: bitnami/prometheus:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /opt/bitnami/prometheus/conf/


      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-config
            items:
              - key: prometheus.properties
                path: prometheus.yml