apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  namespace: dem
  labels:
    app: node-exporter
spec:
  type: ClusterIP
  selector:
    app: node-exporter
  ports:
    - protocol: TCP
      port: 9250
      targetPort: 9250