apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: dem
  labels:
    app: grafana
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000