apiVersion: v1
kind: Service
metadata:
  name: ne-service
  namespace: dem
  labels:
    app: node-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9250'
spec:
  selector:
    app: node-exporter
  ports:
    - protocol: TCP
      port: 9250
      targetPort: 9250
      name: node-exporter